server:
  port: 8080
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jack?characterEncoding=utf-8
    username: root
    password: qq74263827
  #允许dataSource bean定义覆盖
  main:
    allow-bean-definition-overriding: true
  redis:
    host: localhost
    port: 6379
    password: qq74263827
    database: 0 #默认16个数据库，现在是0号数据库
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
jack:
  path: /usr/local/img/
