server:
  port: 8080
spring:
  application:
    name: reggie_take_out
  shardingsphere:
    datasource:
      names:
        master,slave
      #主数据源
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://8.130.102.52:3306/reggie?characterEncoding=utf-8
        username: root
        password: qq74263827
      #从数据源
      slave:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.231.100:3306/reggie?characterEncoding=utf-8
        username: root
        password: qq74263827
    masterslave:
      #读写分离配置
      load-balance-algorithm-type: round_robin #轮询
      #最终的数据源名称
      name: dataSource
      #主库数据源名称
      master-data-source-name: master
      #从库数据源名称列表，多个逗号分隔
      slave-data-source-names: slave
    props:
      sql:
        show: true #开启SQL 显示，默认false
  #允许dataSource bean定义覆盖
  main:
    allow-bean-definition-overriding: true
  redis:
    host: 192.168.231.100
    port: 6379
    password: qq74263827
    database: 0 #默认16个数据库，现在是0号数据库
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
reggie:
  path: D:\IdeaProject\rj_takeout\jpg\
